#!/bin/sh
rga_file() { #THIS IS A JUGAAD
	#rga -l $1 2>&1 1>/dev/null | awk '{if((NR-1)%5==0){print $0}}' | sed 's/..$//'
	rga $1  | awk 'BEGIN{FS=":"}{print $1}' | sort -u
}
findpdf(){

	local file
	file="$(
	rga_file "$1" | \
			fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
				--phony -q "$1" \
				--preview-window="70%:wrap"
	)" &&
	echo "opening $file" &&
	xdg-open "$file"
}
findpdf $1
